import { ShippingRule } from '../types';

export const mockRules: ShippingRule[] = [
  {
    company: '申通',
    region: '北京',
    firstWeight: 1,
    firstPrice: 12,
    continuedPrice: 8,
    throwBase: 6000,
    surfaceFee: 0,
    algorithm: 'firstWeightPlusContinued',
    tierPrices: [],
    temporarySurcharge: 0,
  },
  {
    company: '申通',
    region: '上海',
    firstWeight: 1,
    firstPrice: 10,
    continuedPrice: 6,
    throwBase: 6000,
    surfaceFee: 0,
    algorithm: 'firstWeightPlusContinued',
    tierPrices: [],
    temporarySurcharge: 0,
  },
  {
    company: '韵达',
    region: '北京',
    firstWeight: 1,
    firstPrice: 0,
    continuedPrice: 0,
    throwBase: 6000,
    surfaceFee: 0,
    algorithm: 'tieredPrice',
    tierPrices: [
      { weight: 0.5, price: 2.7 },
      { weight: 1, price: 3.1 },
      { weight: 2, price: 4.5 },
      { weight: 3, price: 5.9 },
    ],
    temporarySurcharge: 0,
  },
  {
    company: '韵达',
    region: '上海',
    firstWeight: 1,
    firstPrice: 0,
    continuedPrice: 0,
    throwBase: 6000,
    surfaceFee: 0,
    algorithm: 'tieredPrice',
    tierPrices: [
      { weight: 0.5, price: 2.5 },
      { weight: 1, price: 2.9 },
      { weight: 2, price: 4.2 },
      { weight: 3, price: 5.5 },
    ],
    temporarySurcharge: 0,
  },
  {
    company: '中通',
    region: '北京',
    firstWeight: 1,
    firstPrice: 15,
    continuedPrice: 10,
    throwBase: 6000,
    surfaceFee: 1,
    algorithm: 'weightTimesContinuedPlusSurface',
    tierPrices: [],
    temporarySurcharge: 0,
  },
  {
    company: '顺丰',
    region: '北京',
    firstWeight: 1,
    firstPrice: 23,
    continuedPrice: 13,
    throwBase: 6000,
    surfaceFee: 0,
    algorithm: 'firstWeightPlusContinued',
    tierPrices: [],
    temporarySurcharge: 0,
  },
];
